/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 8819248feb3836822737f95ef2d48fb4)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./partykit/party");
		durableNamespaces: "PartyServer";
	}
	interface StagingEnv {
		SUPABASE_URL: string;
		SUPABASE_KEY: string;
		ADMIN_TOKEN: string;
		Main: DurableObjectNamespace<import("./partykit/party").PartyServer>;
	}
	interface Env {
		SUPABASE_URL: string;
		SUPABASE_KEY: string;
		ADMIN_TOKEN: string;
		Main: DurableObjectNamespace<import("./partykit/party").PartyServer>;
	}
}
interface Env extends Cloudflare.Env {}
