/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: b28ca341bd1904f6a227fd703b64a14c)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./partykit/party");
		durableNamespaces: "PartyServer";
	}
	interface Env {
		ADMIN_TOKEN: string;
		SUPABASE_URL: string;
		SUPABASE_KEY: string;
		Main: DurableObjectNamespace<import("./partykit/party").PartyServer>;
	}
}
interface Env extends Cloudflare.Env {}
