// ABOUTME: Defines the version 2 operation protocol shared by PlayHTML clients and servers.
// ABOUTME: Describes JSON room state, stable paths, operations, and websocket messages.

/** The wire and persisted-state version implemented by this module. */
export const PROTOCOL_VERSION = 2 as const;

/** The protocol version accepted by version 2 message types. */
export type ProtocolVersion = typeof PROTOCOL_VERSION;

/** A JSON scalar value. */
export type JsonPrimitive = string | number | boolean | null;

/** A JSON object whose properties are protocol values. */
export type JsonObject = { readonly [key: string]: JsonValue };

/** A value that can be stored in room state or sent in an operation. */
export type JsonValue = JsonPrimitive | JsonObject | readonly JsonValue[];

/** A capability name in the top level of room state. */
export type CapabilityName = string;

/** The DOM element ID used within one capability's state. */
export type ElementId = string;

/**
 * User-visible room data, grouped first by capability and then by element ID.
 */
export type RoomState = Record<CapabilityName, Record<ElementId, JsonValue>>;

/** A stable reference to an array item. */
export type ArrayItemPathSegment = {
  readonly itemId: string;
};

/**
 * One step through an element value. Strings address object properties, while
 * array item IDs address array entries without depending on a mutable index.
 */
export type PathSegment = string | ArrayItemPathSegment;

/**
 * A path relative to an element value. An empty path addresses the whole
 * element value.
 */
export type ProtocolPath = readonly PathSegment[];

/** The common address fields carried by every operation. */
export type OperationAddress = {
  readonly capability: CapabilityName;
  readonly elementId: ElementId;
  readonly path: ProtocolPath;
};

/**
 * Stable identities for an array inside an operation value. The path is
 * relative to that value, and an empty path describes the value itself.
 */
export type ValueArrayIdentity = {
  readonly path: ProtocolPath;
  readonly itemIds: readonly string[];
};

/**
 * A JSON value and the stable identities of every array contained within it.
 */
export type OperationValue = {
  readonly value: JsonValue;
  readonly arrays: readonly ValueArrayIdentity[];
};

/** Replaces the JSON value at a path. */
export type SetOperation = OperationAddress &
  OperationValue & {
    readonly type: "set";
  };

/** Selects a new object property for an insert operation. */
export type ObjectInsertTarget = {
  readonly kind: "object";
  readonly key: string;
};

/**
 * Selects a position and stable identity for a new array item. The item ID
 * must be unique within the addressed array.
 */
export type ArrayInsertTarget = {
  readonly kind: "array";
  readonly index: number;
  readonly itemId: string;
};

/** Selects the entry created by an insert operation. */
export type InsertTarget = ObjectInsertTarget | ArrayInsertTarget;

/** Adds a property to an object or an identified item to an array. */
export type InsertOperation = OperationAddress &
  OperationValue & {
    readonly type: "insert";
    readonly target: InsertTarget;
  };

/** Selects an object property for a remove operation. */
export type ObjectRemoveTarget = {
  readonly kind: "object";
  readonly key: string;
};

/** Selects an array item by its stable identity for a remove operation. */
export type ArrayRemoveTarget = {
  readonly kind: "array";
  readonly itemId: string;
};

/** Selects the entry removed from an object or array. */
export type RemoveTarget = ObjectRemoveTarget | ArrayRemoveTarget;

/** Removes one property from an object or one identified item from an array. */
export type RemoveOperation = OperationAddress & {
  readonly type: "remove";
  readonly target: RemoveTarget;
};

/** Adds a finite numeric delta to the number at a path. */
export type IncrementOperation = OperationAddress & {
  readonly type: "increment";
  readonly delta: number;
};

/** A state change accepted by the version 2 apply engine. */
export type Operation =
  | SetOperation
  | InsertOperation
  | RemoveOperation
  | IncrementOperation;

/** A monotonically increasing operation number assigned by the room server. */
export type ServerSequence = number;

/** A room reset generation used to reject operations created before a reset. */
export type RoomGeneration = number;

/** A random per-connection-lifetime client identity generated by the client. */
export type ClientId = string;

/**
 * A per-client sequential mutation number starting at 1. Retries reuse the
 * same number, so the server can deduplicate by tracking the highest applied
 * number per client.
 */
export type MutationId = number;

/**
 * The highest mutation number the server has applied per client. Persisted
 * with the room state so a server restart cannot double-apply a replayed
 * mutation, and returned in snapshots so reconnecting clients can discard
 * confirmed pending operations.
 */
export type LastMutationIds = Record<ClientId, MutationId>;

/**
 * The stable item identities for one array, in the same order as the array's
 * user-visible values.
 */
export type ArrayIdentity = OperationAddress & {
  readonly itemIds: readonly string[];
};

/**
 * A complete room image. Array identities support stable path traversal.
 */
export type RoomSnapshot = {
  readonly state: RoomState;
  readonly arrays: readonly ArrayIdentity[];
  readonly lastMutationIds: LastMutationIds;
};

/** A client request to submit one operation to the room server. */
export type ClientOperationMessage = {
  readonly type: "operation";
  readonly protocolVersion: ProtocolVersion;
  readonly generation: RoomGeneration;
  readonly clientId: ClientId;
  readonly mutationId: MutationId;
  readonly operation: Operation;
};

/** A client request for an authoritative full-state reconnect snapshot. */
export type ClientSnapshotRequestMessage = {
  readonly type: "snapshot-request";
  readonly protocolVersion: ProtocolVersion;
};

/** A message accepted from a version 2 client. */
export type ClientToServerMessage =
  | ClientOperationMessage
  | ClientSnapshotRequestMessage;

/**
 * A server-ordered operation broadcast to every client, including its sender.
 */
export type SequencedOperation = {
  readonly sequence: ServerSequence;
  readonly generation: RoomGeneration;
  readonly clientId: ClientId;
  readonly mutationId: MutationId;
  readonly operation: Operation;
};

/** A server broadcast containing one accepted operation. */
export type ServerOperationMessage = {
  readonly type: "operation";
  readonly protocolVersion: ProtocolVersion;
  readonly payload: SequencedOperation;
};

/** An authoritative full-state snapshot sent on connection or reconnect. */
export type ServerSnapshotMessage = {
  readonly type: "snapshot";
  readonly protocolVersion: ProtocolVersion;
  readonly sequence: ServerSequence;
  readonly generation: RoomGeneration;
  readonly snapshot: RoomSnapshot;
};

/** A stable machine-readable reason for rejecting a client operation. */
export type OperationRejectionCode =
  | "invalid-message"
  | "invalid-operation"
  | "permission-denied"
  | "size-limit"
  | "stale-generation"
  | "unsupported-protocol";

/** A client-visible rejection of an operation that was not applied. */
export type ServerOperationRejectedMessage = {
  readonly type: "operation-rejected";
  readonly protocolVersion: ProtocolVersion;
  readonly sequence: ServerSequence;
  readonly clientId?: ClientId;
  readonly mutationId?: MutationId;
  readonly code: OperationRejectionCode;
  readonly message: string;
};

/** A message sent by the version 2 room server. */
export type ServerToClientMessage =
  | ServerOperationMessage
  | ServerSnapshotMessage
  | ServerOperationRejectedMessage;
