/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config partykit/wrangler.jsonc --include-runtime=false` (hash: be58f97693b46412c7d2db94e17dc0b1)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./partykit/party");
		durableNamespaces: "PartyServer" | "PresenceServer";
	}
	interface StagingEnv {
		SUPABASE_URL: string;
		SUPABASE_KEY: string;
		ADMIN_TOKEN: string;
		Main: DurableObjectNamespace<import("./partykit/party").PartyServer>;
		Presence: DurableObjectNamespace<import("./partykit/party").PresenceServer>;
	}
	interface Env {
		SUPABASE_URL: string;
		SUPABASE_KEY: string;
		ADMIN_TOKEN: string;
		Main: DurableObjectNamespace<import("./partykit/party").PartyServer>;
		Presence: DurableObjectNamespace<import("./partykit/party").PresenceServer>;
	}
}
interface Env extends Cloudflare.Env {}
