// ABOUTME: Declares Worker environment bindings generated from the PartyKit Wrangler config.
// ABOUTME: Keeps Durable Object and secret binding types available to the PartyKit server.
/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config wrangler.jsonc --include-runtime=false` (hash: 683f522fe10ac6fdf638471c47db51be)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./worker");
    durableNamespaces: "PartyServer" | "PresenceServer" | "PartyServerV2";
  }
  interface StagingEnv {
    QUARANTINE_CONTROL: KVNamespace;
    SUPABASE_URL: string;
    SUPABASE_KEY: string;
    ADMIN_TOKEN: string;
    PARTYKIT_BRIDGE_SECRET: string;
    Main: DurableObjectNamespace<import("./worker").PartyServer>;
    Presence: DurableObjectNamespace<import("./worker").PresenceServer>;
    V2: DurableObjectNamespace<import("./worker").PartyServerV2>;
  }
  interface Env {
    QUARANTINE_CONTROL: KVNamespace;
    SUPABASE_URL: string;
    SUPABASE_KEY: string;
    ADMIN_TOKEN: string;
    PARTYKIT_BRIDGE_SECRET: string;
    Main: DurableObjectNamespace<import("./worker").PartyServer>;
    Presence: DurableObjectNamespace<import("./worker").PresenceServer>;
    V2: DurableObjectNamespace<import("./worker").PartyServerV2>;
  }
}
interface Env extends Cloudflare.Env {}
