// ABOUTME: Writes local Supabase credentials for Cloudflare Worker development.
// ABOUTME: Maps one local service-role key to the names used by both Workers.

import { chmodSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { spawnSync } from "node:child_process";

type SupabaseStatus = Record<string, unknown>;

const OUTPUT_PATH = resolve(process.cwd(), ".dev.vars.supabase");

function requiredString(status: SupabaseStatus, name: string): string {
  const value = status[name];
  if (typeof value !== "string" || value.length === 0) {
    throw new Error(`Supabase status did not include ${name}`);
  }
  return value;
}

export function formatLocalSupabaseEnv(status: SupabaseStatus): string {
  const url = requiredString(status, "API_URL");
  const serviceRoleKey = requiredString(status, "SERVICE_ROLE_KEY");

  return [
    "# ABOUTME: Supplies local Supabase credentials to Worker development commands.",
    "# ABOUTME: Generated by `bun run db:local-env`; do not edit or commit.",
    `SUPABASE_URL=${url}`,
    `SUPABASE_KEY=${serviceRoleKey}`,
    `SUPABASE_SECRET_KEY=${serviceRoleKey}`,
    "",
  ].join("\n");
}

export function writeLocalSupabaseEnv(
  status: SupabaseStatus,
  outputPath = OUTPUT_PATH,
): string {
  writeFileSync(outputPath, formatLocalSupabaseEnv(status), {
    encoding: "utf8",
    mode: 0o600,
  });
  chmodSync(outputPath, 0o600);
  return outputPath;
}

function readLocalSupabaseStatus(): SupabaseStatus {
  const result = spawnSync(
    "bunx",
    ["supabase", "status", "--output", "json"],
    { encoding: "utf8" },
  );

  if (result.status !== 0) {
    throw new Error(
      "Could not read local Supabase status. Run `bun run db:start` first.",
    );
  }

  try {
    return JSON.parse(result.stdout) as SupabaseStatus;
  } catch {
    throw new Error("Supabase status returned invalid JSON");
  }
}

if (import.meta.main) {
  const outputPath = writeLocalSupabaseEnv(readLocalSupabaseStatus());
  console.log(`Wrote ${outputPath}`);
}
