// ABOUTME: Tests local Supabase Worker environment generation with real files.
// ABOUTME: Covers credential mapping, file permissions, and missing status values.

import assert from "node:assert/strict";
import {
  mkdtempSync,
  readFileSync,
  rmSync,
  statSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import {
  formatLocalSupabaseEnv,
  writeLocalSupabaseEnv,
} from "./write-local-supabase-env";

const status = {
  API_URL: "http://127.0.0.1:54321",
  SERVICE_ROLE_KEY: "local-service-role-key",
};

test("maps local credentials to both Worker key names", () => {
  assert.equal(
    formatLocalSupabaseEnv(status),
    [
      "# ABOUTME: Supplies local Supabase credentials to Worker development commands.",
      "# ABOUTME: Generated by `bun run db:local-env`; do not edit or commit.",
      "SUPABASE_URL=http://127.0.0.1:54321",
      "SUPABASE_KEY=local-service-role-key",
      "SUPABASE_SECRET_KEY=local-service-role-key",
      "",
    ].join("\n"),
  );
});

test("writes a private local environment file", () => {
  const directory = mkdtempSync(join(tmpdir(), "playhtml-supabase-"));
  const outputPath = join(directory, ".dev.vars.supabase");

  try {
    writeLocalSupabaseEnv(status, outputPath);

    assert.equal(readFileSync(outputPath, "utf8"), formatLocalSupabaseEnv(status));
    assert.equal(statSync(outputPath).mode & 0o777, 0o600);
  } finally {
    rmSync(directory, { recursive: true, force: true });
  }
});

test("rejects incomplete Supabase status output", () => {
  assert.throws(
    () => formatLocalSupabaseEnv({ API_URL: status.API_URL }),
    /Supabase status did not include SERVICE_ROLE_KEY/,
  );
  assert.throws(
    () =>
      formatLocalSupabaseEnv({
        SERVICE_ROLE_KEY: status.SERVICE_ROLE_KEY,
      }),
    /Supabase status did not include API_URL/,
  );
});
