name: pkg.pr.new

on:
  push:
    branches-ignore:
      - main
  pull_request:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install
        run: bun install --frozen-lockfile

      - name: Build packages
        run: bun run build-packages

      - name: Publish preview
        run: bunx pkg-pr-new publish ./packages/playhtml ./packages/react ./packages/common
